import React from 'react'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import AuthProvider from './context/AuthProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Epic Eats',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
      <AuthProvider>
        <NavBar />
      {children}
      {// <Footer />
      }
      </AuthProvider>
      </body>
    </html>
  )
}
